### ISSUE TITLE
Panes jump a little when choose-pane is invoked

### ISSUE THREAD

**Issue by andyngo** [t9md/atom-choose-pane#7]
Not sure if anyone notices this before but there's a slight jump in the panes when choose-pane is activated.

This is due to `atom-panel.bottom` being created when choose-pane is activated. Simple hack to stop this jumping behaviour is to add the following to your styles.less:
```
atom-panel.bottom {
  border: none;
}
```

Screencap:
![1px](https://cloud.githubusercontent.com/assets/278293/23338760/74d3aba6-fc4e-11e6-876c-6b99fe93034c.gif)

**Comment by t9md** [comment]
Thanks, this might be because of change in latest version.
In previous version, panel was created only once.
But in latest, create and destroy panel to read lInout on each start.
Anyway will check and try your suggestion.

**Comment by andyngo** [comment]
Actually, I noticed this in the previous version (0.5.x). Upgraded to the latest (0.6.0) and it's still there. If you inspect element, you can see that there's a 1px height being created at `atom-panel.bottom` when you activate choose-pane. I don't think your commit here is the cause: https://github.com/t9md/atom-choose-pane/commit/6f3a78c284e8b014b711a40c84473017f4730307

<img width="518" alt="screen shot 2017-02-26 at 6 47 00 pm" src="https://cloud.githubusercontent.com/assets/278293/23339020/0f2827a4-fc54-11e6-8e31-57a5c6b169e4.png">

**Comment by andyngo** [comment]
By the way it's more noticeable if you split your pane vertically.

**Comment by t9md** [comment]
Wow! Thanks for quick clarification. Appreciate your help!

**Comment by andyngo** [comment]
No problem. I really love what you're doing for the community. Your packages are a joy to use (I use vim-mode-plus and choose-pane).

**Comment by t9md** [comment]
I checked, and confirmed your suggestion solve the mini-jump issue.
But I think I should not directly set `atom-panel.bottom' 's border to `none`.
This is not scope `choose-pane` owns.

**Comment by andyngo** [comment]
Correct. Should not set `border: none`directly on `atom-panel.bottom`. Do you have any suggestions on how to approach this? I tried adding className to `@panel` but it does not seem to work.

**Comment by t9md** [comment]
panel is shared resource where many core and community package add element into it.
I'm not well familiar how CSS/HTML works.
So I have no idea how to approach, seem to impossible if that border is belonging to atom panel.
Maybe report to atom-core is correct approach?

**Comment by andyngo** [comment]
No problem. I will continue to use the hack that I have above for now. Hopefully this does not present any side-effects. Will proceed to closing this issue now. :)
